# Generated by Django 5.2.4 on 2026-01-19 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZakatCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=12)),
                ('inventory', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receivables', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('liabilities', models.DecimalField(decimal_places=2, max_digits=12)),
                ('zakat_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
